import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{BookOpen,Brain,ClipboardCheck,Layers,BarChart3,Play,Clock,Target,ChevronRight,RotateCcw,CheckCircle2,XCircle,Library,NotebookTabs}from'lucide-react';
import'./style.css';

const syllabus={
'Português':['Compreensão e interpretação de texto','Modos de organização textual','Coesão e coerência textuais','Níveis e variedades da linguagem','Funções da linguagem','Figuras de linguagem','Sinônimos, antônimos, homônimos e parônimos','Polissemia; denotação e conotação','Ortografia e acentuação gráfica','Estrutura e formação de palavras','Flexão nominal e verbal','Coordenação e subordinação','Pronomes: emprego, tratamento e colocação','Tempos e modos verbais','Regência nominal e verbal','Concordância nominal e verbal','Crase','Pontuação'],
'Políticas Públicas de Saúde / SUS':['Constituição Federal — arts. 196 a 200','Lei 8.080/1990 e alterações','Política Nacional de Humanização — HumanizaSUS','Resolução CNS 330/2003 — NOB/RH-SUS','Lei 10.741/2003 — Estatuto da Pessoa Idosa','Portaria 992/2009 — Saúde Integral da População Negra','Portaria 2.836/2011 — Saúde Integral LGBT','Lei 13.146/2015 — Estatuto da Pessoa com Deficiência','Portaria GM/MS 230/2023 — Equidade de Gênero, Raça e Valorização das Trabalhadoras','Portaria GM/MS 1.526/2023 — PNAISPD e RCPD'],
'Conhecimentos Específicos — Farmácia':['Farmacotécnica de produtos não estéreis','Análise de formulações e fórmulas magistrais/oficinais','Estabilidade de formulações extemporâneas','Unitarização de medicamentos sólidos e líquidos','Controle de qualidade','Farmacotécnica de produtos estéreis','Reconstituição, diluição e estabilidade de injetáveis','Fracionamento e dispensação por dose unitária','Nutrição parenteral e formulações de grande volume','Controle microbiológico','Manipulação de quimioterápicos antineoplásicos','Validação de processos','Farmacodinâmica e mecanismos de ação','Interações medicamentosas','Efeitos colaterais e reações adversas','Alergia, tolerância e intoxicação','Medicamentos em populações especiais','Medicamentos em condições especiais','Farmacocinética — conceitos e parâmetros','Metabolismo de medicamentos','Margem terapêutica e posologia','Fatores que alteram a farmacocinética','Monitorização de fármacos','Farmácia clínica e atenção farmacêutica','Uso racional de medicamentos','Problemas relacionados a medicamentos','Monitorização da farmacoterapia','Farmacoepidemiologia e farmacovigilância','Farmacoeconomia','Seleção e padronização de medicamentos','Gestão em farmácia e gestão de estoque','Sistemas informatizados e controle de estoque','Gestão da farmácia hospitalar','Sistemas de distribuição de medicamentos','Biossegurança','Código de Ética profissional']};
const seedQuestions=[
{id:1,s:'Português',t:'Crase',q:'Assinale a alternativa em que o uso da crase está correto:',o:['Entreguei o relatório à diretora.','Cheguei à pé cedo.','Refiro-me à pessoas experientes.','Voltarei daqui à duas horas.'],a:0,e:'Há crase antes de substantivo feminino determinado quando ocorre a fusão da preposição “a” com o artigo “a”.'},
{id:2,s:'Políticas Públicas de Saúde / SUS',t:'Lei 8.080/1990 e alterações',q:'A Lei nº 8.080/1990 trata principalmente de:',o:['Organização e funcionamento dos serviços de saúde','Código Penal sanitário','Regulamentação exclusiva da saúde suplementar','Criação do Conselho Federal de Medicina'],a:0,e:'A Lei 8.080/1990 dispõe sobre as condições para promoção, proteção e recuperação da saúde e sobre a organização e funcionamento dos serviços correspondentes.'},
{id:3,s:'Conhecimentos Específicos — Farmácia',t:'Farmacocinética — conceitos e parâmetros',q:'Biodisponibilidade corresponde, em termos gerais, à:',o:['Fração e velocidade com que o fármaco alcança a circulação sistêmica','Capacidade do fármaco de se ligar apenas ao receptor','Quantidade total excretada sem metabolização','Dose máxima permitida em 24 horas'],a:0,e:'Biodisponibilidade descreve a extensão e a velocidade de chegada do princípio ativo à circulação sistêmica.'},
{id:4,s:'Conhecimentos Específicos — Farmácia',t:'Farmacodinâmica e mecanismos de ação',q:'Farmacodinâmica estuda principalmente:',o:['O que o fármaco faz ao organismo','O que o organismo faz ao fármaco','Somente a excreção renal','Somente a absorção intestinal'],a:0,e:'Farmacodinâmica aborda efeitos, mecanismos de ação e relação concentração–efeito.'},
{id:5,s:'Políticas Públicas de Saúde / SUS',t:'Constituição Federal — arts. 196 a 200',q:'Segundo a Constituição Federal, a saúde é:',o:['Direito de todos e dever do Estado','Benefício exclusivo do trabalhador formal','Competência exclusiva dos municípios','Serviço facultativo da União'],a:0,e:'O art. 196 estabelece a saúde como direito de todos e dever do Estado.'},
{id:6,s:'Português',t:'Compreensão e interpretação de texto',q:'Na interpretação de textos, uma inferência é:',o:['Uma conclusão construída a partir de informações explícitas e implícitas','A simples cópia de uma frase','Um erro de ortografia','Uma regra fixa de pontuação'],a:0,e:'Inferir é chegar a uma conclusão apoiada em pistas e relações presentes no texto.'}
];
const seedCards=[
{id:1,s:'SUS',front:'Art. 196 da Constituição',back:'Saúde é direito de todos e dever do Estado.'},
{id:2,s:'Farmácia',front:'Farmacodinâmica',back:'Estuda o que o fármaco faz ao organismo: efeitos e mecanismos de ação.'},
{id:3,s:'Farmácia',front:'Farmacocinética',back:'Estuda o que o organismo faz ao fármaco: absorção, distribuição, metabolismo e excreção.'},
{id:4,s:'Português',front:'Crase',back:'Fusão de dois sons/vogais “a”, geralmente preposição + artigo feminino.'}
];
const initial={minutes:0,answers:[],sessions:[],cards:seedCards.map(c=>({...c,next:0,level:0})),topicStatus:{}};
const load=()=>{try{return{...initial,...JSON.parse(localStorage.getItem('estudafarma-v2')||'{}')}}catch{return initial}};
function App(){const[state,setState]=useState(load);const[tab,setTab]=useState('Início');useEffect(()=>localStorage.setItem('estudafarma-v2',JSON.stringify(state)),[state]);
const stats=useMemo(()=>{const n=state.answers.length,c=state.answers.filter(x=>x.correct).length;return{n,c,rate:n?Math.round(c/n*100):0,errors:n-c}},[state.answers]);
const domain=(subject)=>{const ans=state.answers.filter(x=>x.subject===subject);if(!ans.length)return 0;const accuracy=ans.filter(x=>x.correct).length/ans.length;const touched=new Set(ans.map(x=>x.topic)).size/(syllabus[subject]?.length||1);return Math.round((accuracy*.75+touched*.25)*100)};
const overall=Math.round(Object.keys(syllabus).reduce((a,s)=>a+domain(s),0)/3);
const reset=()=>{if(confirm('Apagar todo o seu histórico local e reiniciar?'))setState(initial)};
return <div className="app"><aside><h1>Estuda<span>Farma</span></h1><small>Preparação inteligente</small>{['Início','Matérias','Questões','Simulados','Flashcards','Caderno de Erros','Biblioteca','Desempenho'].map(x=><button key={x} className={tab===x?'on':''} onClick={()=>setTab(x)}>{x}</button>)}<button className="reset" onClick={reset}><RotateCcw size={14}/> Reiniciar dados</button></aside><main><header><div><h2>{tab}</h2><p>Concurso • Farmacêutico</p></div><div className="streak">🔥 {Math.min(30,new Set(state.sessions.map(x=>x.date)).size)} dias</div></header>
{tab==='Início'&&<Home state={state} setState={setState} stats={stats} domain={domain} overall={overall} go={setTab}/>} {tab==='Matérias'&&<Subjects domain={domain}/>} {tab==='Questões'&&<Questions state={state} setState={setState}/>} {tab==='Simulados'&&<Simulado state={state} setState={setState}/>} {tab==='Flashcards'&&<Flashcards state={state} setState={setState}/>} {tab==='Caderno de Erros'&&<Errors state={state}/>} {tab==='Biblioteca'&&<Biblioteca/>} {tab==='Desempenho'&&<Performance state={state} stats={stats} domain={domain}/>}</main></div>}
function Home({state,setState,stats,domain,overall,go}){const start=()=>{setState(s=>({...s,minutes:s.minutes+25,sessions:[...s.sessions,{date:new Date().toISOString().slice(0,10),minutes:25}]}));go('Questões')};return <><section className="hero"><div><span>PLANO DE HOJE</span><h2>Estude onde seu ganho pode ser maior.</h2><p>Prioridade: Conhecimentos Específicos — Farmácia.</p><button onClick={start}><Play size={18}/> Começar 25 min</button></div><div className="ring"><b>{overall}%</b><small>domínio</small></div></section><div className="metrics"><Card icon={<Clock/>} n={`${Math.floor(state.minutes/60)}h ${state.minutes%60}m`} t="tempo registrado"/><Card icon={<ClipboardCheck/>} n={stats.n} t="questões"/><Card icon={<Target/>} n={`${stats.rate}%`} t="acertos"/><Card icon={<Layers/>} n={state.cards.filter(c=>c.next<=Date.now()).length} t="flashcards para revisar"/></div><h3>Domínio por matéria</h3><div className="subjects">{Object.entries(syllabus).map(([s,topics])=><article key={s} onClick={()=>go('Matérias')}><div><BookOpen/><div><b>{s}</b><p>{topics.length} tópicos do edital</p></div><strong>{domain(s)}%</strong></div><progress value={domain(s)} max="100"/></article>)}</div><div className="grid"><section><h3><Brain/> Estudo inteligente</h3><p>• Faça 10 questões do assunto prioritário.</p><p>• Revise os erros antes de avançar.</p><p>• Resolva flashcards vencidos.</p><button className="primary" onClick={()=>go('Questões')}>Ir para questões <ChevronRight size={16}/></button></section><section><h3><BarChart3/> Seu histórico</h3><div className="big">{stats.rate}%</div><p>{stats.c} acertos em {stats.n} respostas.</p><p>{stats.errors} erros registrados para revisão.</p></section></div></>}
function Subjects({domain}){return <div className="stack">{Object.entries(syllabus).map(([s,topics])=><section className="panel" key={s}><div className="sectionTitle"><div><h3>{s}</h3><p>{topics.length} tópicos cadastrados</p></div><strong>{domain(s)}%</strong></div><progress value={domain(s)} max="100"/><div className="topicList">{topics.map((t,i)=><div key={t}><span>{String(i+1).padStart(2,'0')}</span>{t}</div>)}</div></section>)}</div>}
function Questions({state,setState}){const[i,setI]=useState(0),[picked,setPicked]=useState(null),[checked,setChecked]=useState(false);const q=seedQuestions[i%seedQuestions.length];const answer=()=>{if(picked===null||checked)return;const correct=picked===q.a;setState(s=>({...s,answers:[...s.answers,{id:Date.now(),questionId:q.id,subject:q.s,topic:q.t,correct,picked,date:new Date().toISOString()}]}));setChecked(true)};const next=()=>{setI(x=>(x+1)%seedQuestions.length);setPicked(null);setChecked(false)};return <section className="quiz panel"><div className="eyebrow">{q.s} • {q.t}</div><h3>{q.q}</h3><div className="options">{q.o.map((o,n)=><button key={o} disabled={checked} className={`${picked===n?'selected':''} ${checked&&n===q.a?'correct':''} ${checked&&picked===n&&n!==q.a?'wrong':''}`} onClick={()=>setPicked(n)}><span>{String.fromCharCode(65+n)}</span>{o}</button>)}</div>{checked&&<div className={picked===q.a?'feedback ok':'feedback bad'}>{picked===q.a?<CheckCircle2/>:<XCircle/>}<div><b>{picked===q.a?'Resposta correta':'Resposta incorreta'}</b><p>{q.e}</p></div></div>}<div className="actions"><button className="primary" onClick={checked?next:answer} disabled={picked===null}>{checked?'Próxima questão':'Responder'}</button></div></section>}
function Simulado({state,setState}){const[running,setRunning]=useState(false),[answers,setAnswers]=useState({}),[result,setResult]=useState(null);const qs=seedQuestions;const finish=()=>{const c=qs.filter(q=>Number(answers[q.id])===q.a).length;const rows=qs.map(q=>({id:Date.now()+q.id,questionId:q.id,subject:q.s,topic:q.t,correct:Number(answers[q.id])===q.a,picked:Number(answers[q.id]),date:new Date().toISOString(),simulado:true}));setState(s=>({...s,answers:[...s.answers,...rows]}));setResult({c,n:qs.length});setRunning(false)};if(!running&&!result)return <section className="empty"><ClipboardCheck size={44}/><h2>Simulado rápido</h2><p>{qs.length} questões misturando Português, SUS e Farmácia. O resultado entra no seu desempenho.</p><button className="primary" onClick={()=>setRunning(true)}>Iniciar simulado</button></section>;if(result)return <section className="empty"><h2>{Math.round(result.c/result.n*100)}%</h2><p>Você acertou {result.c} de {result.n} questões.</p><button className="primary" onClick={()=>{setAnswers({});setResult(null);setRunning(true)}}>Fazer novamente</button></section>;return <section className="panel"><h3>Simulado em andamento</h3>{qs.map((q,idx)=><div className="simQ" key={q.id}><b>{idx+1}. {q.q}</b>{q.o.map((o,n)=><label key={o}><input type="radio" name={`q${q.id}`} value={n} checked={String(answers[q.id])===String(n)} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/>{o}</label>)}</div>)}<button className="primary" disabled={Object.keys(answers).length<qs.length} onClick={finish}>Finalizar simulado</button></section>}
function Flashcards({state,setState}){const[dueIndex,setDueIndex]=useState(0),[flip,setFlip]=useState(false);const due=state.cards.filter(c=>c.next<=Date.now());if(!due.length)return <section className="empty"><Layers size={44}/><h2>Revisões em dia</h2><p>Não há flashcards vencidos agora.</p></section>;const card=due[dueIndex%due.length];const grade=(good)=>{setState(s=>({...s,cards:s.cards.map(c=>c.id===card.id?{...c,level:good?Math.min(6,c.level+1):0,next:Date.now()+(good?Math.max(1,2**c.level):1)*86400000}:c)}));setFlip(false);setDueIndex(x=>x+1)};return <section className="flashWrap"><div className="eyebrow">{card.s} • revisão espaçada</div><button className="flash" onClick={()=>setFlip(!flip)}><small>{flip?'RESPOSTA':'PERGUNTA'}</small><strong>{flip?card.back:card.front}</strong><span>Clique para virar</span></button>{flip&&<div className="grade"><button onClick={()=>grade(false)}>Errei / difícil</button><button className="primary" onClick={()=>grade(true)}>Acertei</button></div>}</section>}
function Errors({state}){const wrong=state.answers.filter(x=>!x.correct).slice().reverse();return <section className="panel"><h3><NotebookTabs/> Caderno de Erros</h3>{!wrong.length?<p className="muted">Seus erros aparecerão aqui automaticamente.</p>:wrong.map((x,i)=>{const q=seedQuestions.find(q=>q.id===x.questionId);return <div className="errorRow" key={x.id||i}><div><b>{x.topic}</b><small>{x.subject}</small><p>{q?.q}</p></div><span>Revisar</span></div>})}</section>}
function Biblioteca(){return <section className="empty"><Library size={44}/><h2>Biblioteca de materiais</h2><p>A estrutura está pronta para a próxima etapa: PDFs, apostilas, legislação e anotações vinculados aos tópicos do edital.</p><div className="notice">No GitHub Pages os arquivos podem ser exibidos, mas importação persistente e login serão adicionados com banco de dados.</div></section>}
function Performance({state,stats,domain}){return <><div className="metrics"><Card icon={<Clock/>} n={`${state.minutes} min`} t="estudados"/><Card icon={<ClipboardCheck/>} n={stats.n} t="respostas"/><Card icon={<Target/>} n={`${stats.rate}%`} t="taxa de acerto"/><Card icon={<NotebookTabs/>} n={stats.errors} t="erros"/></div><section className="panel"><h3>Desempenho por matéria</h3>{Object.keys(syllabus).map(s=><div className="perf" key={s}><div><b>{s}</b><span>{domain(s)}%</span></div><progress value={domain(s)} max="100"/></div>)}</section></>}
function Card({icon,n,t}){return <article className="card">{icon}<div><b>{n}</b><small>{t}</small></div></article>}
createRoot(document.getElementById('root')).render(<App/>);
